#!/usr/bin/env bash
# Function to display
display_info(){
local domain="$1"
local subdomain="$2"
local record_type=$(dig +short -t A "$subdomain.$domain")
local destination=$(dig +short "$subdomain.$domain")

if [ -z "$record_type" ]; then
	record_type="CNAME"
else
	record_type="A"
fi

echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ $# -eq 2 ]; then
	domain="$1"
	subdomain="$2"
	display_info "$domain" "$subdomain"
else
	subdomains=("www" "lb-01" "web-01" "web-02")

	domain="$1"
	for subdomain in "${subdomains[@]}"; do
		display_info "$domain" "$subdomain"
	done
fi

