#!/usr/bin/env bash
# the script that will help to transfer file
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#initialize the variable
file_path="$1"
username="$3"
shh_key="$4"
ip="$2"

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$ip:~/"
