#!/usr/bin/env bash
#create a bash script that install ngnx server

sudo apt-get update && apt-get install -y nginx

# check if nginx is still running
if pgrep -x "nginx" >/dev/null; then
	echo "Nginx is already running"
else
	sudo service nginx start
fi

echo "Hello World!" | sudo tee /var/www/html/index.html

#checking if nginx is not listenning on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
