#!/usr/bin/env bash
# function to redirect the user to the error page

# creation of redirect.conf
echo "
	server {
		listen 80;
		server_name localhost;

		location /redirect_me {
			return 301 /new_page;
		}
		location /new_page {
			root /var/www/html;
			index index.html;
		}
	}
" | sudo tee /etc/nginx/conf.d/redirect.conf
sudo /etc/init.d/nginx restart
