#!/usr/bin/env bash
# the function that
sudo apt-get update | sudo apt-get install nginx -y
hostname=$(hostname)
cat <<EOL | sudo tee /etc/nginx/conf.d/custom_response_header.conf
server {
	listen 80;
	server_name _;

	location / {
		add_header X-Served-By "$hostname";
	}

}
EOL
sudo nginx -t
sudo systemctl reload nginx
