#!/usr/bin/env bash
# installing and configuring haproxy

# Install HaProxy and system update
sudo apt update && sudo apt install haproxy -y >> /dev/null

# configure HAProxy
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
	log /dev/log local0
	log /dev/log local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log global
	mode http
	option httplog
	option dontlognull
	timeout connect 5000
	timeout client 50000
	timeout server 50000

frontend http-in
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server web-01 320368-web-01:80 check
	server web-02 320368-web-02:80 check
EOL

# update the hostname to -lb-01
sudo hostnamectl set-hostname 320368-lb-01

sudo systemctl enable haproxy
sudo systemctl start haproxy
