#!/usr/bin/env bash
# the program that ping the given argument

#check if there is argument
if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
ping -c 5 "$1"