#!/usr/bin/env bash
# module that deals with fixing ngnx debugging
sudo apt-get update && sudo apt-get install nginx -y
sudo service nginx start

# configure to listen on port 80
cp -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
