#!/usr/bin/env bash
# This file tends to modify /etc/hosts file

cp /etc/hosts ~/hosts.new
sed -i "s/12.0.0.1/127.0.0.2/g" ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

cp ~/hosts.new /etc/hosts